import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { parseSpriteNames } from '../src/parse_sprite_names.ts';

const root = resolve(import.meta.dirname, '..');
const sourcePath = resolve(root, 'spritenames.txt');
const outPath = resolve(root, 'src/sprite_names.generated.ts');

const source = readFileSync(sourcePath, 'utf8');
const result = parseSpriteNames(source);

if (result.errors.length > 0) {
  console.error('spritenames.txt has parse errors:');
  for (const err of result.errors) console.error('  ' + err);
  process.exit(1);
}

const byCategory = new Map<string, Array<{ frame: number; name: string }>>();
for (const sprite of result.sprites) {
  if (sprite.isAlias) continue;
  let arr = byCategory.get(sprite.category);
  if (!arr) {
    arr = [];
    byCategory.set(sprite.category, arr);
  }
  arr.push({ frame: sprite.frame, name: sprite.name });
}
const categories = [...byCategory.keys()].sort();

const lines: string[] = [
  '// AUTO-GENERATED by scripts/generate-sprite-names.ts from spritenames.txt.',
  '// Do not edit by hand — run "npm run generate:names" after editing the source.',
  '',
  'export const SPRITE_NAMES = {',
];
for (const category of categories) {
  lines.push(`  ${category}: {`);
  const sprites = byCategory.get(category)!.sort((a, b) => a.name.localeCompare(b.name));
  for (const { frame, name } of sprites) {
    lines.push(`    ${name}: ${frame},`);
  }
  lines.push('  },');
}
lines.push('} as const;', '');
lines.push('export type SpriteCategory = keyof typeof SPRITE_NAMES;');
lines.push('');

writeFileSync(outPath, lines.join('\n'));

const named = result.sprites.filter((s) => !s.isAlias).length;
const aliased = result.sprites.filter((s) => s.isAlias).length;
console.log(
  `Generated ${outPath}: ${named} named sprites across ${categories.length} categories, ${aliased} aliases, ${result.emptyFrames.length} empty cells.`,
);
